# 感知机

In [8]:
from sklearn import datasets
import numpy as np

In [10]:
iris = datasets.load_iris()

In [11]:
X = iris.data[:,[2, 3]]
y = iris.target

In [16]:
print(np.unique(y))

[0 1 2]


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [19]:
np.bincount(y) # 各个值的个数

array([50, 50, 50], dtype=int64)

In [20]:
np.bincount(y_train)

array([35, 35, 35], dtype=int64)

In [21]:
np.bincount(y_test)

array([15, 15, 15], dtype=int64)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [23]:
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [28]:
from sklearn.linear_model import Perceptron

In [30]:
ppn = Perceptron(n_iter_no_change=40, eta0=0.1, random_state=1)

In [31]:
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.1, n_iter_no_change=40, random_state=1)

In [32]:
y_pred = ppn.predict(X_test_std)
miss_classified = (y_pred != y_test).sum()

In [33]:
miss_classified

8

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_pred, y_test)

0.8222222222222222

In [42]:
from sklearn.datasets import load_iris
import pandas as pd

In [43]:
iris = load_iris()

In [44]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [45]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [46]:
df['label'] = iris.target

In [47]:
df['label']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: label, Length: 150, dtype: int32